
local monarch = require 'monarch.monarch'
local button = require 'common.button'

function init(self)
	gui.set_render_order(3)
	msg.post('.', 'acquire_input_focus')

	self.buttons = {}
	self.buttons.play = button.new(self, 'play', function ()
		monarch.show(monarch.scr.victorina)
	end)
end

function on_input(self, action_id, action)
	for _, btn in pairs(self.buttons) do
		if btn:on_input(action) then
			return true
		end
	end
end

